spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/auth}
    username: ${SPRING_DATASOURCE_USERNAME:akshat}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret: ${JWT_SECRET:super-secret-256-bit-key-super-secret}
  expiration: ${JWT_EXPIRATION_MS:900000}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

server:
  port: ${SERVER_PORT:8081}

security:
  refresh-token:
    ttl-days: 30
    pepper: change-me-in-prod

management:
  endpoints:
    web:
      exposure:
        include: health,info
